#!/bin/bash
# Enable Surface Tablet Controls Extension

echo "========================================="
echo "Surface Tablet Controls - Quick Setup"
echo "========================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
   echo "ERROR: Don't run this script as root/sudo!"
   echo "Run it as your regular user."
   exit 1
fi

echo "✓ Extension files installed at:"
echo "  ~/.local/share/gnome-shell/extensions/surface-tablet-controls@custom/"
echo ""

echo "✓ Optimized gesture config applied:"
echo "  ~/.config/touchegg/touchegg.conf"
echo ""

echo "Restarting touchegg daemon..."
sudo systemctl restart touchegg
echo "✓ Touchegg restarted"
echo ""

echo "========================================="
echo "IMPORTANT: To enable the extension"
echo "========================================="
echo ""
echo "You need to restart GNOME Shell:"
echo ""
echo "METHOD 1 (Quick - X11 only):"
echo "  1. Press Alt+F2"
echo "  2. Type: r"
echo "  3. Press Enter"
echo ""
echo "METHOD 2 (Works on Wayland too):"
echo "  1. Log out"
echo "  2. Log back in"
echo ""
echo "After restart, you should see a tablet icon"
echo "in your top bar (right side)."
echo ""
echo "========================================="
echo "Features Available:"
echo "========================================="
echo ""
echo "TOP BAR ICON:"
echo "  • Toggle touchscreen on/off"
echo "  • Toggle auto-rotation on/off"
echo "  • Quick disable (30s) - Perfect for typing!"
echo ""
echo "GESTURES (iPad-like):"
echo "  • 3-finger swipe up: Show overview"
echo "  • 3-finger swipe down: Minimize window"
echo "  • 3-finger swipe left/right: Switch workspace"
echo "  • 4-finger pinch in: Show desktop"
echo "  • 4-finger swipe up: App switcher"
echo "  • 2-finger tap: Right click"
echo "  • 2-finger pinch: Zoom in/out"
echo ""
echo "BROWSER GESTURES:"
echo "  • 2-finger swipe left/right: Back/Forward"
echo "  • 2-finger swipe up/down: Page up/down"
echo ""
echo "========================================="
echo "Troubleshooting:"
echo "========================================="
echo ""
echo "If icon doesn't appear:"
echo "  journalctl -f -o cat /usr/bin/gnome-shell | grep surface"
echo ""
echo "If gestures are laggy:"
echo "  sudo systemctl restart touchegg"
echo ""
echo "========================================="
